{
 "title": "Flask App Metrics Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Visitor Count Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(website_visitors_total{service=\"flask-app-service\"}[5m])"
    }
   ]
  },
  {
   "title": "Max Visitors Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(website_visitors_total{service=\"flask-app-service\"})"
    }
   ]
  },
  {
   "title": "Flask Total Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(website_visitors_total{service=\"flask-app-service\"}[5m])"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(flask_http_requests_total{service=\"flask-app-service\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"default\"}[5m])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\"}"
    }
   ]
  }
 ]
}