apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.port }}
  clusterIP: None
