name: Destroy Infrastructure

### if you want to change the cloud provider, change the cd command in the workflow (step Terraform Init, step Terraform Destroy)


on:
  workflow_dispatch: # Manual trigger

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
      - name: Terraform init
        run: |
          ls
          pwd
          cd terraform-aws
          terraform init
    
      - name: Terraform Destroy
        run: |
          cd terraform-aws
          terraform destroy -auto-approve
